# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix multiplication test
#' 
#' Testing
#' @param x
#' @param y
#' @return the multiplied matrix
#' @export
#' @useDynLib
matrix_mult_armadillo <- function(x, y) {
    .Call('_vaxedemic_matrix_mult_armadillo', PACKAGE = 'vaxedemic', x, y)
}

#' Matrix multiplication
#' 
#' Uses RcppEigen to multiply two matrices quickly
#' @param x the first matrix
#' @param y the second matrix
#' @return the multiplied matrix
#' @export
#' @useDynLib
matrix_mult <- function(x, y) {
    .Call('_vaxedemic_matrix_mult', PACKAGE = 'vaxedemic', x, y)
}

#' Simulation
#'
#' Wow
#' @export
stochastic_simulation <- function(S, I, R, beta, gamma, Kdelta, K1, Mm1, div, ndays, n_age_groups, n_countries) {
    .Call('_vaxedemic_stochastic_simulation', PACKAGE = 'vaxedemic', S, I, R, beta, gamma, Kdelta, K1, Mm1, div, ndays, n_age_groups, n_countries)
}

