# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cpp useless function
#'
#' Another useless function to test package development
#' @param x completely meaningless
#' @return something else
#' @export
#' @useDynLib vaxedemic
initial_test_cpp <- function(x) {
    .Call('_vaxedemic_initial_test_cpp', PACKAGE = 'vaxedemic', x)
}

